name: Update site

# Run action three times per hour.
on:
  schedule:
    - cron: "15 * * * *"
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Netlify build hook
      env:
        NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
      run: |
        curl -X POST -d {} $NETLIFY_BUILD_HOOK
