name: Hourly site build

# Build site once an hour
on:
  schedule:
    - cron: "10 * * * *"
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Netlify build hook
      env:
        NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
      run: |
        curl -X POST -d {} $NETLIFY_BUILD_HOOK
